name: Publish
run-name: ${{ inputs.publish_type == 'Dry Run' && 'Publish (Dry Run)' || 'Publish' }}

on:
  workflow_dispatch:
    inputs:
      publish_type:
        description: "Publish options"
        required: true
        default: "Publish"
        type: choice
        options:
          - Publish
          - Dry Run
      version:
        description: "Version to publish (default: latest release)"
        required: true
        type: string
        default: latest

defaults:
  run:
    working-directory: .

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-24.04
    outputs:
      release_version: ${{ steps.version-output.outputs.version }}
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Check branch
        if: ${{ inputs.publish_type != 'Dry Run' }}
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/main" ]]; then
            echo "==================================="
            echo "[!] Can only publish from the 'main' branch"
            echo "==================================="
            exit 1
          fi

      - name: Output version
        id: version-output
        run: |
          if [[ "${{ inputs.version }}" == "latest" || "${{ inputs.version }}" == "" ]]; then
            VERSION=$(curl  "https://api.github.com/repos/bitwarden/mcp-server/releases" | jq -c '.[] | select(.tag_name | contains("v")) | .tag_name' | head -1 | grep -ohE '20[0-9]{2}\.([1-9]|1[0-2])\.[0-9]+')
            echo "Latest Released Version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Release Version: ${{ inputs.version }}"
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub deployment
        if: ${{ inputs.publish_type != 'Dry Run' }}
        uses: chrnorm/deployment-action@55729fcebec3d284f60f5bcabbd8376437d696b1 # v2.0.7
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          initial-status: "in_progress"
          environment: "NPM"
          description: "Deployment ${{ steps.version-output.outputs.version }} from branch ${{ github.ref_name }}"
          task: release

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-24.04
    needs: setup
    permissions:
      packages: read
      id-token: write
    env:
      _PKG_VERSION: ${{ needs.setup.outputs.release_version }}

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: refs/tags/v${{ env._PKG_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "24.6.0" # npm 11.5.1 or later is required to publish w/ OIDC
          registry-url: "https://registry.npmjs.org/"

      - name: Install Husky
        run: npm install -g husky

      - name: Download and set up artifact
        run: |
          wget https://github.com/${{ github.repository }}/releases/download/v${{ env._PKG_VERSION }}/mcp-server-${{ env._PKG_VERSION }}.zip
          unzip mcp-server-${{ env._PKG_VERSION }}.zip

      - name: Publish to NPM (Dry Run)
        if: ${{ inputs.publish_type == 'Dry Run' }}
        run: npm publish --access public --dry-run

      - name: Publish to NPM
        if: ${{ inputs.publish_type != 'Dry Run' }}
        run: npm publish --access public

  publish-ghpr:
    name: Publish to GitHub Package Registry
    runs-on: ubuntu-24.04
    needs: setup
    env:
      _PKG_VERSION: ${{ needs.setup.outputs.release_version }}
    permissions:
      packages: write

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: refs/tags/v${{ env._PKG_VERSION }}

      - name: Download and set up artifact
        run: |
          wget https://github.com/${{ github.repository }}/releases/download/v${{ env._PKG_VERSION }}/mcp-server-${{ env._PKG_VERSION }}.zip
          unzip mcp-server-${{ env._PKG_VERSION }}.zip

      - name: Set up GHPR
        run: |
          echo 'registry="https://npm.pkg.github.com/"' > ./.npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ./.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Husky
        run: npm install -g husky

      - name: Publish to GHPR (Dry Run)
        if: ${{ inputs.publish_type == 'Dry Run' }}
        run: npm publish --access public --registry=https://npm.pkg.github.com/ --userconfig=./.npmrc --dry-run

      - name: Publish to GHPR
        if: ${{ inputs.publish_type != 'Dry Run' }}
        run: npm publish --access public --registry=https://npm.pkg.github.com/  --userconfig=./.npmrc

  publish-ghcr:
    name: Publish release as latest
    runs-on: ubuntu-24.04
    needs: setup
    env:
      _RELEASE_TAG: ${{ needs.setup.outputs.release_version }}
      _IMAGE_NAME: ghcr.io/bitwarden/mcp-server
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Dry Run - Pull, tag, and push release as latest
        if: ${{ inputs.publish_type == 'Dry Run' }}
        run: |
          docker pull ${{ env._IMAGE_NAME }}:${{ env._RELEASE_TAG }}
          docker tag ${{ env._IMAGE_NAME }}:${{ env._RELEASE_TAG }} ${{ env._IMAGE_NAME }}:latest

      - name: Pull, tag, and push release as latest
        if: ${{ inputs.publish_type != 'Dry Run' }}
        run: |
          docker pull ${{ env._IMAGE_NAME }}:${{ env._RELEASE_TAG }}
          docker tag ${{ env._IMAGE_NAME }}:${{ env._RELEASE_TAG }} ${{ env._IMAGE_NAME }}:latest
          docker push ${{ env._IMAGE_NAME }}:latest

  update-deployment:
    name: Update deployment status
    runs-on: ubuntu-24.04
    needs:
      - setup
      - publish-npm
      - publish-ghpr
    permissions:
      contents: read
      deployments: write

    if: ${{ always() && inputs.publish_type != 'Dry Run' }}
    steps:
      - name: Check if any job failed
        if: contains(needs.*.result, 'failure')
        run: exit 1

      - name: Update deployment status to Success
        if: ${{ inputs.publish_type != 'Dry Run' && success() }}
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          state: "success"
          deployment-id: ${{ needs.setup.outputs.deployment_id }}

      - name: Update deployment status to Failure
        if: ${{ inputs.publish_type != 'Dry Run' && failure() }}
        uses: chrnorm/deployment-status@9a72af4586197112e0491ea843682b5dc280d806 # v2.0.3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          state: "failure"
          deployment-id: ${{ needs.setup.outputs.deployment_id }}
